config-ver: 3

duplication:
  command:
    enable: true
    multiply-times: 2
    max-amount: 2333
  item-frame:
    enable: false
    possibility: 10 # percent
  chicken:
    xin-mode: false
    xin-mode-periods:
      - 15
      - 30
      - 45
      - 0
    click-mode: false
    click-mode-cooldown: 3 # second
  donkey:
    xin-mode: false
    org-mode: false
    org-mode-allow-boat-chain: false
  mine-and-place:
    enable: false
    amount: 10


limits:
  crystal-speed:
    enable: false
    limit: 300 # ms
  ender-portal-entities:
    enable: false
    disable-ender-teleport: false # only enable when the main feature is enabled
    limit: 10 # entities per second



suicide-enable: true

messages:
  success-dupe: "&e&lSuccessfully duped items!"
  crystal-too-fast: "" # be empty better, %remain-seconds%
  suicide: "" # the same as â†‘
